# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
services:
  - xvfb
julia:
  - 1.3
  - 1.5
  - nightly
notifications:
  email: false
before_script:
  - echo $DISPLAY